###########################
#       AntiTetoNether    #
###########################

AtivarAntiTetoNether: true
raseAntiTetoDoNetherTOP: "&4Proíbido"
raseAntiTetoDoNetherDOWN: "Você não pode passar!"


###########################
#       AntiDanoDoVoid    #
###########################

AtivarAntiDanoDoVoid: true
PermissaoAntiVoid: "hfix.void" #Não deixe essa variável vazia.


###########################
#       FakePlayers       #
###########################

AtivarFakePlayers: true
FakePlayers:
  - "[IF]"
  - "[Mekanism]"
  - "[OutroFakePlayer]"