##############################
#       AntiCeilingNether    #
##############################
EnableAntiCeilingNether: true
PhraseAntiCeilingDoNetherTOP: "&4WARNING"
PhraseAntiCeilingDoNetherDOWN: "You can not pass!"


#############################
#       NoVoidDamage        #
#############################
EnableAntiDanoDoVoid: true
PermissionAntiVoid: "hfix.void" #Don't leave this variable empty.
AntiVoidPhrase: "You were saved by a mysterious force."


#######################
#       BanItems      #
#######################
EnableBlockBans: true
BannedPhrase: "The item you are trying to use is banned, you cannot do anything with it."
BannedItems:
  - "BEDROCK"


#######################
#       LagVerify     #
#######################
EnableLagVerify: true


###########################
#       LimitMobChunk     #
###########################
EnableLimitMobChunk: true
MobsPerChunk: 20


###########################
#       FakePlayers       #
###########################
EnableFakePlayers: true
FakePlayers:
  - "[IF]"
  - "[Mekanism]"
  - "[AnotherFakePlayer]"

###########################
#       BlackList         #
###########################
MobsBlackList:
  - "ENDER_DRAGON"
  - "ENDER_CRYSTAL"
  - "ARMOR_STAND"
  - "VILLAGER"
  - "VINDICATOR"
  - "ITEM_FRAME"