###########################
#       AntiNetherY       #
###########################

AtivarAntNetherY: true
FraseAntiNetherYTOP: "&4Proíbido"
FraseAntiNetherYDOWN: "Você não pode passar!"

###########################
#       FakePlayers       #
###########################

AtivarFakePlayers: true
FakePlayers:
  - "[IF]"
  - "[Mekanism]"
  - "[OutroFakePlayer]"