###########################
#       AntiTetoNether    #
###########################

AtivarAntiTetoNether: true
FraseAntiTetoDoNetherTOP: "&4Proíbido"
FraseAntiTetoDoNetherDOWN: "Você não pode passar!"


###########################
#       AntiDanoDoVoid    #
###########################

AtivarAntiDanoDoVoid: true
PermissaoAntiVoid: "hfix.void" #Não deixe essa variável vazia.


#######################################
#       AtivarBanimentosDeBlocos      #
#######################################

AtivarBanimentosDeBlocos: true
FraseDeBanidos: "Você não pode manipular esse bloco, ele está banido do servidor."
BlocosBanidos:
  - "minecraft:bedrock"


###########################
#       FakePlayers       #
###########################

AtivarFakePlayers: true
FakePlayers:
  - "[IF]"
  - "[Mekanism]"
  - "[OutroFakePlayer]"